
server:
  host: 127.0.0.1
  port: 8085

database:
  username: movierental
  password: movierental
  dbname: movie_rental
  host: 127.0.0.1
  port: 5432
  sslmode: disable

databasetest:
  username: movierentaltest
  password: movierentaltest
  dbname: movie_rentaltest
  host: 192.168.106.2
  port: 5432
  sslmode: disable